name: "Repo Sync"

on:
  schedule:
    # at 07:15 AM every day
    - cron: "15 7 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    name: Repo sync

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      # https://github.com/repo-sync/github-sync
      - name: Repo sync
        uses: repo-sync/github-sync@3832fe8e2be32372e1b3970bbae8e7079edeec88 # v2.3.0
        with:
          source_repo: https://git.yoctoproject.org/git/poky
          source_branch: "*" # Sync all branches
          destination_branch: "*" # Sync all branches
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sync_tags: "true"
